# HandlerExceptionResolver를 활용하기  


**예외 마무리**
예외가 발생하면 WAS까지 예외가 던져지고, WAS에서 오류 페이지 정보를 찾아서 다시 `/error`를 호출한다. 해당 과정은 굳이 핸들러에서 예외가 발생할 경우 WAS까지 가서 또 다시 `/error`를 호출해주는게 복잡하고 비효율적이라는 생각이 든다.

서버 내부에서 예외를 잡았다면, `ExceptionResolver`가 에러를 인터셉터하여 내부에서 예외를 처리해가지고 결과만 WAS에 넘겨주면된다.
WAS에서 다시 `/error`를 호출해주지 않아도 된다는 것.

### HandlerExceptionResolver를 활용해서 예외를 핸들링 하기전에 먼저 사용자 정의 예외를 하나 추가해보자

```java
package hello.exception.exception;  
  
public class UserException extends RuntimeException {  
    /**  
     * Constructs a new runtime exception with {@code null} as its  
     * detail message.  The cause is not initialized, and may subsequently be     * initialized by a call to {@link #initCause}.  
     */    public UserException() {  
        super();  
    }   
  
    /**  
     * Constructs a new runtime exception with the specified detail message.     * The cause is not initialized, and may subsequently be initialized by a     * call to {@link #initCause}.  
     *     * @param message the detail message. The detail message is saved for  
     *                later retrieval by the {@link #getMessage()} method.  
     */    public UserException(String message) {  
        super(message);  
    }  
  
    /**  
     * Constructs a new runtime exception with the specified detail message and     * cause.  <p>Note that the detail message associated with     * {@code cause} is <i>not</i> automatically incorporated in  
     * this runtime exception's detail message.     *     * @param message the detail message (which is saved for later retrieval  
     *                by the {@link #getMessage()} method).  
     * @param cause   the cause (which is saved for later retrieval by the  
     *                {@link #getCause()} method).  (A {@code null} value is  
     *                permitted, and indicates that the cause is nonexistent or     *                unknown.)     * @since 1.4  
     */    public UserException(String message, Throwable cause) {  
        super(message, cause);  
    }  
  
    /**  
     * Constructs a new runtime exception with the specified cause and a     * detail message of {@code (cause==null ? null : cause.toString())}  
     * (which typically contains the class and detail message of  
     * {@code cause}).  This constructor is useful for runtime exceptions  
     * that are little more than wrappers for other throwables.     *     * @param cause the cause (which is saved for later retrieval by the  
     *              {@link #getCause()} method).  (A {@code null} value is  
     *              permitted, and indicates that the cause is nonexistent or     *              unknown.)     * @since 1.4  
     */    public UserException(Throwable cause) {  
        super(cause);  
    }  
  
    /**  
     * Constructs a new runtime exception with the specified detail     * message, cause, suppression enabled or disabled, and writable     * stack trace enabled or disabled.     *     * @param message            the detail message.  
     * @param cause              the cause.  (A {@code null} value is permitted,  
     *                           and indicates that the cause is nonexistent or unknown.)     * @param enableSuppression  whether or not suppression is enabled  
     *                           or disabled     * @param writableStackTrace whether or not the stack trace should  
     *                           be writable     * @since 1.7  
     */    protected UserException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {  
        super(message, cause, enableSuppression, writableStackTrace);  
    }  
}
```

`UserExcpetion`을 처리할 클래스를 정의해준다

```java
@GetMapping("/api/members/{id}")  
public MemberDto getMember(@PathVariable String id) {  
    if (id.equals("ex"))  
        throw new RuntimeException("잘못된 사용자");  
  
    if (id.equals("bad"))  
        throw new IllegalArgumentException("잘못된 요청");  
  
    if (id.equals("user-ex"))  
        throw new UserException("사용자 오류");  
  
    return new MemberDto(id, "hello" + id);  
}
```
`ApiExceptionController`에서 `UserException`을 던져준다.

그 뒤 `ExceptionResovler`를 구현할 `UserHandlerException`을 만들어준다.
```java
@Slf4j  
public class UserHandlerExceptionResolver implements HandlerExceptionResolver {  
    private final ObjectMapper objectMapper = new ObjectMapper();  
    @Override  
    public ModelAndView resolveException(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, Object o, Exception e) {  
        // 에러 발생 시 Response에 헤더 정보를 담아서 JSON으로 변환후 보내는 것  
        try {  
            if (e instanceof UserException) {  
                // 두가지의 경우가 있음 JSON으로 처리하는 경우, Html로 처리하는 경우  
                log.info("UserException to 400");  
                // Response Header를 만들어줌.  
                 httpServletResponse.setStatus(HttpServletResponse.SC_BAD_REQUEST);  
                 //헤더에 대한 정보를 끌고옴  
                if ("application/json".equals(httpServletRequest.getHeader("accept"))) {  
                    Map<String, Object> errorResult = new HashMap<>();  
                    //에러 클래스를 담아둠.  
                    errorResult.put("ex", e.getClass());  
                    //에러 메시지를 담아둠  
                    errorResult.put("message", e.getMessage());  
                    //JSON으로 들어온 정보를 담아둔 Map을 String으로 변경  
                    String result = objectMapper.writeValueAsString(errorResult);  
  
                    // 결과 반환 시 헤더의 정보를 다시 씌워줌  
                    httpServletResponse.setContentType("application/json");  
                    httpServletResponse.setCharacterEncoding("UTF-8");  
  
                    // String으로 변환 된 Map을 다시 Json 형태의 String으로 바디에 덮어씌워줌  
                    httpServletResponse.getWriter().write(result);  
                    return new ModelAndView();  
                } else {  
                    // text/html 뷰 템플릿의 뷰를 렌더링 해  
                    return new ModelAndView("error/500");  
                }  
            }  
        } catch (IOException ex) {  
            log.error("resolve exception", ex);  
        }  
        return null;  
    }  
}
```
HTTP 요청 해더의 `ACCEPT` 값이 `application/json` 이면 JSON으로 오류를 내려주고, 그 외 경우에는 error/ 500에 있는 HTML 오류 페이지를 보여준다.

그 뒤 `WebConfig`클래스에 에러 클래스를 등록해준다.

```java
@Configuration  
public class WebConfig implements WebMvcConfigurer {  
  
    @Override  
    public void extendHandlerExceptionResolvers(List<HandlerExceptionResolver> resolvers) {  
        resolvers.add(new MyHandlerExceptionResolver());  
        resolvers.add(new UserHandlerExceptionResolver());  
    }  
}
```

**실행**
```json
 {     "ex": "hello.exception.exception.UserException",
 "message": "사용자 오류" 
 {
```

**정리**
여기서는 ExceptionResolver에서 모든것을 한번에 처리한 경우이다.  원래는 WAS에 sendError메서드를 이용하여 에러의 대한 정보를 담아서 다시 WAS까지 보내서 요청을 수행했었다.

`ExceptionResolver`를 활용하여 컨트롤러에서 예외가 발생했을 때 응답헤더에 대한 구조를 다 담아서 반환하면 서블릿 컨테이너까지 예외가 전달되지 않고,  디스패처 서블릿에서 예외를 다 처리한 후 `new ModelAndView`를 담아서 WAS에 보내버린다. 그럼 결과적으로 WAS 입장에서는 예외 처리가 된것이 아닌 정상 처리가 된 것이다. 이렇게 **예외를 이곳에서 모두 처리할 수 있다는 것이 `ExceptionResovler`의 핵심이다**.

서블릿 컨테이너까지 예외가 올라가면 복잡하고 지저분하게 추가 프로세스들이 실행이 되는데, `ExceptionResolver`를 사용하면 예외처리가 Spring MVC에서 처리가 된다. 



  
